In [2]:
import numpy as np
import pandas as pd

# Data Structures in Pandas

## Pandas makes use of two different data structures
    *Series
    *Data Frame
    
### Series represents data in a 1D form while data frames represent data in a 2D tabular form

In [ ]:
#pandas Series: one-dimensional array with labels

In [11]:
#obtain series from Python dictionaries (data structure for storing key-value pairs)
# keys of dictionaries act as index or label for values
dict={'a' : 3, 'b' : 'cat', 'c' : 2.5}
pd.Series(dict) #

a      3
b    cat
c    2.5
dtype: object

In [4]:
oneD = pd.Series([100, 'cat', 310, 'gog', 500], ['Amy', 'Bobby', 'Cat', 'Don', 'Emma'])
oneD

Amy      100
Bobby    cat
Cat      310
Don      gog
Emma     500
dtype: object

In [10]:
oneD = pd.Series([100, 'cat', 310, 'gog', 500], index=['Amy', 'Bobby', 'Cat', 'Don', 'Emma']) #the second list contains index
#index is the label of values
oneD

Amy      100
Bobby    cat
Cat      310
Don      gog
Emma     500
dtype: object

In [5]:
oneD.loc[['Cat','Emma']] #loc is a label-location based indexer for selection by labels- Cat and Donna

Cat     310
Emma    500
dtype: object

In [6]:
oneD[[0,3,4]] #extract the data at index 0, 3 and 4

Amy     100
Don     gog
Emma    500
dtype: object

In [7]:
oneD.iloc[1] #.iloc is primarily integer position based (from 0 to length-1 of the axis). access index 1

'cat'

In [8]:
#check if there is a cat in the series index

'cat' in oneD

False

In [9]:
'Cat' in oneD

True

In [ ]:
#DataFrames- 2D data structure. Stores data in tabular form (rows and columns)
#<class 'pandas.core.frame.DataFrame'>

In [14]:
d = {'A' : pd.Series([100., 200., 300.], index=['apple', 'pear', 'orange']),
     'B' : pd.Series([111., 222., 333., 4444.], index=['apple', 'pear', 'orange', 'melon'])}

In [15]:
df = pd.DataFrame(d)
print(df) #when there are no values corresponding to an index then we have NaN

            A       B
apple   100.0   111.0
melon     NaN  4444.0
orange  300.0   333.0
pear    200.0   222.0

In [19]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [16]:
df.index #list index values

Index([u'apple', u'melon', u'orange', u'pear'], dtype='object')

In [17]:
df.columns #column names

Index([u'A', u'B'], dtype='object')

In [18]:
pd.DataFrame(df, index=['orange', 'melon', 'apple'], columns=['A']) #specify which row/index and column we want to retain

            A
orange  300.0
melon     NaN
apple   100.0

# Read in CSV Files

In [ ]:
import pandas as pd

In [29]:
import os
os.getcwd()

'F:\\Python_ML\\Course6_Python4DS\\MLData_n_Script\\section5'

In [30]:
#Read in a very simple CSV file

file="F:\\Python_ML\\Course6_Python4DS\\MLData_n_Script\\section5\\Resp2.csv"
df1=pd.read_csv(file)
df1.head()

   experience  respiration
0           0         3.94
1           0         4.26
2           0         4.16
3           0         3.76
4           0         4.07

In [39]:
#Read in CSV when the seperator is ;
file="F:\\Python_ML\\Course6_Python4DS\\MLData_n_Script\\section5\\winequality-red.csv"
df1=pd.read_csv(file)
df1=pd.read_csv(file, sep = ";")
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [40]:
#Read in .txt file
#df1=pd.read_csv("bostonTxt.txt") #tab seperated
df1=pd.read_csv("bostonTxt.txt", sep = "\t")
df1.head()

     MV  INDUS   NOX     RM  TAX    PT  LSTAT
0  24.0   2.31  53.8  6.575  296  15.3   4.98
1  21.6   7.07  46.9  6.421  242  17.8   9.14
2  34.7   7.07  46.9  7.185  242  17.8   4.03
3  33.4   2.18  45.8  6.998  222  18.7   2.94
4  36.2   2.18  45.8  7.147  222  18.7   5.33

# Read in Excel File

In [ ]:
import pandas as pd

In [6]:
import os

In [7]:
os.getcwd()

'F:\\Python_ML\\Course6_Python4DS\\MLData_n_Script\\section5'

In [8]:
file="F:\\Python_ML\\Course6_Python4DS\\MLData_n_Script\\section5\\boston1.xls"

# Load spreadsheet
xl = pd.ExcelFile(file)

# Print the sheet names
print(xl.sheet_names)

[u'Sheet1', u'Sheet2']

In [5]:
# Load a sheet into a DataFrame by name: df1
df1 = xl.parse('Sheet1')

df1.head()

,MV,INDUS,NOX,RM,TAX,PT,LSTAT,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,24.0,2.31,53.8,6.575,296,15.3,4.98,NaN,NaN,Subset of Boston housing tract
1,21.6,7.07,46.9,6.421,242,17.8,9.14,NaN,NaN,data of Harrison and Rubinfeld
2,34.7,7.07,46.9,7.185,242,17.8,4.03,NaN,NaN,(1978). Each case is one U.S.
3,33.4,2.18,45.8,6.998,222,18.7,2.94,NaN,NaN,Census tract in the Boston area.
4,36.2,2.18,45.8,7.147,222,18.7,5.33,NaN,NaN,NaN

In [10]:
#import the library used to query a website
import urllib2
from bs4 import BeautifulSoup

In [23]:
#specify the url
#wiki = "https://en.wikipedia.org/wiki/List_of_state_and_union_territory_capitals_in_India"

wiki = "https://en.wikipedia.org/wiki/List_of_World_Heritage_Sites_in_South_Korea"

#Query the website and return the html to the variable 'page'
page = urllib2.urlopen(wiki)

In [25]:
#Parse the html in the 'page' variable, and store it in Beautiful Soup format
soup = BeautifulSoup(page)

In [27]:
print soup.prettify()

In [ ]:
##Find all the links within page’s <a> tags. <a href> </a> stores web links

In [28]:
soup.find_all("a")

[]

In [15]:
all_links=soup.find_all("a")
for l in all_links:
    print l.get("href")

None
/wiki/Wikipedia:Featured_lists
#mw-head
#p-search
/wiki/States_and_union_territories_of_India
/wiki/File:Flag_of_India.svg
/wiki/List_of_states_and_territories_of_India_by_area
/wiki/List_of_states_and_union_territories_of_India_by_population
/wiki/ISO_3166-2:IN
None
/wiki/List_of_Indian_states_by_Child_Nutrition
/wiki/Indian_states_and_territories_ranking_by_crime_rate
/wiki/Indian_states_ranked_by_economic_freedom
/wiki/Indian_states_ranking_by_households_having_electricity
/wiki/Indian_states_ranking_by_fertility_rate
/wiki/Forest_cover_by_state_in_India
/wiki/List_of_Indian_states_and_union_territories_by_GDP
/wiki/List_of_Indian_states_by_GDP_per_capita
/wiki/List_of_Indian_states_and_territories_by_highest_point
/wiki/Indian_states_ranked_by_HIV_awareness
/wiki/List_of_Indian_states_and_territories_by_Human_Development_Index
/wiki/Indian_states_ranking_by_families_owning_house
/wiki/Indian_states_ranking_by_household_size
/wiki/Indian_states_and_territories_ranked_by_incidents_of_human_trafficking
/wiki/Indian_states_ranking_by_institutional_delivery
/wiki/List_of_Indian_states_by_life_expectancy_at_birth
/wiki/Indian_states_ranking_by_literacy_rate
/wiki/Indian_states_ranking_by_media_exposure
/wiki/Indian_states_ranked_by_number_of_vehicles
/wiki/List_of_states_and_union_territories_of_India_by_voters
/wiki/Indian_states_and_union_territories_ranked_by_prevalence_of_open_defecation
/wiki/List_of_Indian_state_and_union_territory_name_etymologies
/wiki/List_of_states_and_territories_of_India_by_number_of_places_of_worship
/wiki/Indian_states_and_territories_ranked_by_poverty
/wiki/States_of_India_by_installed_power_capacity
/wiki/Indian_states_and_union_territories_ranked_by_riots_rate
/wiki/Indian_states_ranking_by_drinking_water
/wiki/Indian_states_and_territories_ranked_by_safety_of_women
/wiki/Indian_states_ranked_by_school_enrollment_rate
/wiki/Indian_states_and_territories_ranking_by_sex_ratio
/wiki/Indian_states_ranked_by_suicide
/wiki/States_of_India_by_tax_revenues
/wiki/Indian_states_ranked_by_ease_of_doing_business
/wiki/Indian_states_ranking_by_television_ownership
/wiki/Indian_states_and_union_territories_ranked_by_availability_of_toilets
/wiki/Indian_states_by_transport_network
/wiki/Indian_states_ranking_by_underweight_people
/wiki/Indian_states_ranked_by_unemployment
/wiki/Indian_states_ranking_by_vaccination_coverage
/wiki/Template:Lists_of_states_and_territories_of_India
/wiki/Template_talk:Lists_of_states_and_territories_of_India
//en.wikipedia.org/w/index.php?title=Template:Lists_of_states_and_territories_of_India&action=edit
/wiki/India
/wiki/Demographics_of_India
/wiki/Democracy
/wiki/Federalism
/wiki/Constitutional_republic
/wiki/Parliamentary_system
/wiki/States_and_territories_of_India
#cite_note-FOOTNOTELibrary_of_Congress2004-1
/wiki/Puducherry
/wiki/National_Capital_Territory_of_Delhi
/wiki/Westminster_system
/wiki/States_Reorganisation_Act
#cite_note-FOOTNOTESharma200749-2
/wiki/Vidhan_Sabha
/wiki/High_Courts_of_India
#List
#Explanatory_notes
#Citations
#References
#External_links
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=edit&section=1
/wiki/Andaman_and_Nicobar_Islands
/wiki/Port_Blair
/wiki/Kolkata
/wiki/Andhra_Pradesh
/wiki/Hyderabad,_India
/wiki/Amaravati
#cite_note-3
#cite_note-4
#cite_note-5
/wiki/Amaravati
#cite_note-6
/wiki/High_Court_of_Judicature_at_Hyderabad
/wiki/Kurnool
/wiki/Arunachal_Pradesh
/wiki/Itanagar
/wiki/Guwahati
/wiki/Assam
/wiki/Dispur
/wiki/Guwahati
/wiki/Shillong
#cite_note-8
/wiki/Bihar
/wiki/Patna
/wiki/Chandigarh
/wiki/Chandigarh
#cite_note-10
/wiki/Chhattisgarh
/wiki/Naya_Raipur
#cite_note-11
/wiki/Bilaspur,_Chhattisgarh
/wiki/Dadra_and_Nagar_Haveli
/wiki/Silvassa
/wiki/Mumbai
/wiki/Panaji
/wiki/Daman_and_Diu
/wiki/Daman,_Daman_and_Diu
/wiki/Mumbai
/wiki/Ahmedabad
/wiki/Panaji
/wiki/Delhi_NCT
/wiki/New_Delhi
/wiki/Goa
/wiki/Panaji
#cite_note-13
/wiki/Porvorim
/wiki/Mumbai
/wiki/Gujarat
/wiki/Gandhinagar
/wiki/Ahmedabad
/wiki/Ahmedabad
/wiki/Haryana
/wiki/Chandigarh
/wiki/Himachal_Pradesh
/wiki/Shimla
/wiki/Dharamsala
#cite_note-14
/wiki/Bilaspur,_Himachal_Pradesh
/wiki/Jammu_and_Kashmir
/wiki/Srinagar
/wiki/Jammu
/wiki/Jharkhand
/wiki/Ranchi
/wiki/Karnataka
/wiki/Bengaluru
/wiki/Kerala
/wiki/Thiruvananthapuram
/wiki/Kochi
/wiki/Lakshadweep
/wiki/Kavaratti
/wiki/Kochi
/wiki/Madhya_Pradesh
/wiki/Bhopal
/wiki/Jabalpur
/wiki/Nagpur
#cite_note-18
/wiki/Maharashtra
/wiki/Mumbai
#cite_note-19
/wiki/Nagpur
#cite_note-20
#cite_note-22
/wiki/Manipur
/wiki/Imphal
/wiki/Meghalaya
/wiki/Shillong
/wiki/Mizoram
/wiki/Aizawl
/wiki/Guwahati
/wiki/Nagaland
/wiki/Kohima
/wiki/Guwahati
/wiki/Odisha
/wiki/Bhubaneswar
/wiki/Cuttack
/wiki/Cuttack
/wiki/Puducherry
/wiki/Puducherry
/wiki/Chennai
/wiki/Madras
/wiki/Punjab,_India
/wiki/Chandigarh
/wiki/Rajasthan
/wiki/Jaipur
/wiki/Jodhpur
/wiki/Sikkim
/wiki/Gangtok
#cite_note-24
/wiki/Tamil_Nadu
/wiki/Chennai
#cite_note-25
/wiki/Telangana
/wiki/Hyderabad
#cite_note-26
/wiki/Tripura
/wiki/Agartala
/wiki/Uttar_Pradesh
/wiki/Lucknow
/wiki/Allahabad
/wiki/Uttarakhand
/wiki/Dehradun
#cite_note-28
/wiki/Nainital
/wiki/West_Bengal
/wiki/Kolkata
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=edit&section=2
#cite_ref-5
/wiki/Andhra_Pradesh_Reorganisation_Act,_2014
/wiki/Amaravati
#cite_ref-8
#cite_note-FOOTNOTEBaruah1999xiii-7
#cite_ref-10
#cite_note-FOOTNOTEMenonBanerjea20025-9
#cite_ref-11
/wiki/Chhattisgarh
/wiki/Naya_Raipur
#cite_ref-13
/wiki/Portugal
#cite_note-FOOTNOTERing1996288-12
#cite_ref-18
/wiki/Central_Provinces_and_Berar
#cite_note-FOOTNOTEBoland-CreweLea2002155-15
/wiki/Madhya_Pradesh
#cite_note-FOOTNOTEBoland-CreweLea2002155-15
#cite_note-FOOTNOTEKum.C4.81ra1998136-16
/wiki/Central_Provinces_and_Berar
/wiki/Vidarbha
/wiki/Madhya_Pradesh
/wiki/Bombay_State
/wiki/Maharashtra
#cite_note-FOOTNOTEKini197434.E2.80.9335-17
#cite_ref-19
/wiki/Bombay_Presidency
/wiki/Bombay_State
#cite_ref-20
/wiki/Maharashtra
#cite_note-FOOTNOTEKini197434.E2.80.9335-17
/wiki/Maharashtra
#cite_ref-22
#cite_note-FOOTNOTEKhandewale198921-21
#cite_ref-24
#cite_note-FOOTNOTESpate1953200-23
#cite_ref-25
/wiki/Madras_Presidency
#cite_ref-26
/wiki/Andhra_Pradesh_Reorganisation_Act,_2014
/wiki/Andhra_Pradesh_Capital_City
#cite_ref-28
/wiki/Uttarakhand
/wiki/Gairsain
#cite_note-FOOTNOTESatiKumar20049.E2.80.9310-27
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=edit&section=3
#cite_ref-FOOTNOTELibrary_of_Congress2004_1-0
#CITEREFLibrary_of_Congress2004
#cite_ref-FOOTNOTESharma200749_2-0
#CITEREFSharma2007
#cite_ref-3
http://www.gulte.com/news/56377/After-2200-Years-Amaravati-Gets-Back-Power
#cite_ref-4
http://www.ap.gov.in/
#cite_ref-6
http://www.gulte.com/news/56377/After-2200-Years-Amaravati-Gets-Back-Power
#cite_ref-FOOTNOTEBaruah1999xiii_7-0
#CITEREFBaruah1999
#cite_ref-FOOTNOTEMenonBanerjea20025_9-0
#CITEREFMenonBanerjea2002
#cite_ref-FOOTNOTERing1996288_12-0
#CITEREFRing1996
#cite_ref-14
http://www.hillpost.in/2017/01/dharamshala-declared-second-capital-of-himachal/107991/
#cite_ref-FOOTNOTEBoland-CreweLea2002155_15-0
#cite_ref-FOOTNOTEBoland-CreweLea2002155_15-1
#CITEREFBoland-CreweLea2002
#cite_ref-FOOTNOTEKum.C4.81ra1998136_16-0
#CITEREFKum.C4.81ra1998
#cite_ref-FOOTNOTEKini197434.E2.80.9335_17-0
#cite_ref-FOOTNOTEKini197434.E2.80.9335_17-1
#CITEREFKini1974
#cite_ref-FOOTNOTEKhandewale198921_21-0
#CITEREFKhandewale1989
#cite_ref-FOOTNOTESpate1953200_23-0
#CITEREFSpate1953
#cite_ref-FOOTNOTESatiKumar20049.E2.80.9310_27-0
#CITEREFSatiKumar2004
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=edit&section=4
https://books.google.com/books?id=8k-irMMTnywC&pg=PR13
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-0-8122-3491-6
https://books.google.com/books?id=JrNCaYCriicC&pg=PA155
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-1-85743-148-3
http://lcweb2.loc.gov/frd/cs/profiles/India.pdf
/wiki/Library_of_Congress_Country_Studies
/wiki/Library_of_Congress
/wiki/Federal_Research_Division
https://books.google.com/books?id=_SDhC12S7q4C&pg=PA21
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-81-7099-134-2
https://books.google.com/books?id=H6DQEoh0EJ8C&pg=PA95
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-81-7022-553-9
https://books.google.com/books?id=46HcFvAv96sC&pg=PA34
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-0-88386-524-8
https://books.google.com/books?id=nKqF_AgDd4gC&pg=PA136
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-81-7022-691-8
https://books.google.com/books?id=sB1AhvY2BSEC
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-0-7546-5424-7
https://books.google.com/books?id=gm_tzXsC12gC
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-81-7764-518-7
http://www.aponline.gov.in/quick%20links/hist-cult/history_post.html
https://books.google.com/books?id=vWLRxJEU49EC&pg=PA288
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-1-884964-04-6
https://books.google.com/books?id=ct6YMRvYJQ4C&pg=PA9
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-81-7099-898-3
https://books.google.com/books?id=srDytmFE3KMC
/wiki/Prentice_Hall
/wiki/International_Standard_Book_Number
/wiki/Special:BookSources/978-81-203-3246-1
https://books.google.com/books?id=DrgNAAAAQAAJ
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=edit&section=5
https://web.archive.org/web/20130528025659/http://www.nic.in/states
http://legislativebodiesinindia.nic.in/
/wiki/Template:State_and_Union_Territory_capitals_of_India
/wiki/Template_talk:State_and_Union_Territory_capitals_of_India
//en.wikipedia.org/w/index.php?title=Template:State_and_Union_Territory_capitals_of_India&action=edit
/wiki/India
/wiki/States_and_territories_of_India
None
/wiki/India
/wiki/Agartala
/wiki/Aizawl
/wiki/Amaravati
/wiki/Bangalore
/wiki/Bhopal
/wiki/Bhubaneswar
/wiki/Chandigarh
/wiki/Chennai
/wiki/Daman,_Daman_and_Diu
/wiki/Dehradun
/wiki/New_Delhi
/wiki/Dispur
/wiki/Gandhinagar
/wiki/Gangtok
/wiki/Hyderabad
/wiki/Imphal
/wiki/Itanagar
/wiki/Jaipur
/wiki/Jammu_(city)
/wiki/Kavaratti
/wiki/Kohima
/wiki/Kolkata
/wiki/Lucknow
/wiki/Mumbai
/wiki/Panaji
/wiki/Patna
/wiki/Pondicherry
/wiki/Port_Blair
/wiki/Raipur
/wiki/Ranchi
/wiki/Shillong
/wiki/Shimla
/wiki/Silvassa
/wiki/Srinagar
/wiki/Thiruvananthapuram
https://en.wikipedia.org/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&oldid=788810468
/wiki/Help:Category
/wiki/Category:States_and_territories_of_India-related_lists
/wiki/Category:Indian_capital_cities
/wiki/Category:Lists_of_cities_in_India
/wiki/Category:Lists_of_capitals_of_country_subdivisions
/wiki/Category:Cities_and_towns_in_India_by_state_or_territory
/wiki/Category:Featured_lists
/wiki/Special:MyTalk
/wiki/Special:MyContributions
/w/index.php?title=Special:CreateAccount&returnto=List+of+state+and+union+territory+capitals+in+India
/w/index.php?title=Special:UserLogin&returnto=List+of+state+and+union+territory+capitals+in+India
/wiki/List_of_state_and_union_territory_capitals_in_India
/wiki/Talk:List_of_state_and_union_territory_capitals_in_India
/wiki/List_of_state_and_union_territory_capitals_in_India
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=edit
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=history
/wiki/Main_Page
/wiki/Main_Page
/wiki/Portal:Contents
/wiki/Portal:Featured_content
/wiki/Portal:Current_events
/wiki/Special:Random
https://donate.wikimedia.org/wiki/Special:FundraiserRedirector?utm_source=donate&utm_medium=sidebar&utm_campaign=C13_en.wikipedia.org&uselang=en
//shop.wikimedia.org
/wiki/Help:Contents
/wiki/Wikipedia:About
/wiki/Wikipedia:Community_portal
/wiki/Special:RecentChanges
//en.wikipedia.org/wiki/Wikipedia:Contact_us
/wiki/Special:WhatLinksHere/List_of_state_and_union_territory_capitals_in_India
/wiki/Special:RecentChangesLinked/List_of_state_and_union_territory_capitals_in_India
/wiki/Wikipedia:File_Upload_Wizard
/wiki/Special:SpecialPages
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&oldid=788810468
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&action=info
https://www.wikidata.org/wiki/Special:EntityPage/Q3518799
/w/index.php?title=Special:CiteThisPage&page=List_of_state_and_union_territory_capitals_in_India&id=788810468
/w/index.php?title=Special:Book&bookcmd=book_creator&referer=List+of+state+and+union+territory+capitals+in+India
/w/index.php?title=Special:ElectronPdf&page=List+of+state+and+union+territory+capitals+in+India&action=show-selection-screen&coll-download-url=%2Fw%2Findex.php%3Ftitle%3DSpecial%3ABook%26bookcmd%3Drender_article%26arttitle%3DList%2Bof%2Bstate%2Band%2Bunion%2Bterritory%2Bcapitals%2Bin%2BIndia%26returnto%3DList%2Bof%2Bstate%2Band%2Bunion%2Bterritory%2Bcapitals%2Bin%2BIndia%26oldid%3D788810468%26writer%3Drdf2latex
/w/index.php?title=List_of_state_and_union_territory_capitals_in_India&printable=yes
https://as.wikipedia.org/wiki/%E0%A6%AD%E0%A6%BE%E0%A7%B0%E0%A6%A4%E0%A7%B0_%E0%A7%B0%E0%A6%BE%E0%A6%9C%E0%A7%8D%E0%A6%AF_%E0%A6%86%E0%A7%B0%E0%A7%81_%E0%A6%95%E0%A7%87%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A7%8D%E0%A7%B0%E0%A7%80%E0%A6%AF%E0%A6%BC%E0%A6%B6%E0%A6%BE%E0%A6%B8%E0%A6%BF%E0%A6%A4_%E0%A6%85%E0%A6%9E%E0%A7%8D%E0%A6%9A%E0%A6%B2%E0%A6%B8%E0%A6%AE%E0%A7%82%E0%A6%B9%E0%A7%B0_%E0%A7%B0%E0%A6%BE%E0%A6%9C%E0%A6%A7%E0%A6%BE%E0%A6%A8%E0%A7%80%E0%A7%B0_%E0%A6%A4%E0%A6%BE%E0%A6%B2%E0%A6%BF%E0%A6%95%E0%A6%BE
https://bn.wikipedia.org/wiki/%E0%A6%AD%E0%A6%BE%E0%A6%B0%E0%A6%A4%E0%A7%87%E0%A6%B0_%E0%A6%B0%E0%A6%BE%E0%A6%9C%E0%A7%8D%E0%A6%AF_%E0%A6%93_%E0%A6%95%E0%A7%87%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A7%8D%E0%A6%B0%E0%A6%B6%E0%A6%BE%E0%A6%B8%E0%A6%BF%E0%A6%A4_%E0%A6%85%E0%A6%9E%E0%A7%8D%E0%A6%9A%E0%A6%B2%E0%A6%B8%E0%A6%AE%E0%A7%82%E0%A6%B9%E0%A7%87%E0%A6%B0_%E0%A6%B0%E0%A6%BE%E0%A6%9C%E0%A6%A7%E0%A6%BE%E0%A6%A8%E0%A7%80%E0%A6%B0_%E0%A6%A4%E0%A6%BE%E0%A6%B2%E0%A6%BF%E0%A6%95%E0%A6%BE
https://hi.wikipedia.org/wiki/%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4_%E0%A4%95%E0%A5%87_%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A5%8D%E0%A4%AF%E0%A5%8B%E0%A4%82_%E0%A4%94%E0%A4%B0_%E0%A4%B8%E0%A4%82%E0%A4%98_%E0%A4%95%E0%A5%8D%E0%A4%B7%E0%A5%87%E0%A4%A4%E0%A5%8D%E0%A4%B0%E0%A5%8B%E0%A4%82_%E0%A4%95%E0%A5%80_%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A4%A7%E0%A4%BE%E0%A4%A8%E0%A4%BF%E0%A4%AF%E0%A4%BE%E0%A4%81
https://id.wikipedia.org/wiki/Daftar_ibu_kota_negara_bagian_dan_wilayah_di_India
https://kn.wikipedia.org/wiki/%E0%B2%AD%E0%B2%BE%E0%B2%B0%E0%B2%A4%E0%B2%A6_%E0%B2%B0%E0%B2%BE%E0%B2%9C%E0%B3%8D%E0%B2%AF_%E0%B2%AE%E0%B2%A4%E0%B3%8D%E0%B2%A4%E0%B3%81_%E0%B2%95%E0%B3%87%E0%B2%82%E0%B2%A6%E0%B3%8D%E0%B2%B0%E0%B2%BE%E0%B2%A1%E0%B2%B3%E0%B2%BF%E0%B2%A4_%E0%B2%AA%E0%B3%8D%E0%B2%B0%E0%B2%A6%E0%B3%87%E0%B2%B6%E0%B2%97%E0%B2%B3_%E0%B2%B0%E0%B2%BE%E0%B2%9C%E0%B2%A7%E0%B2%BE%E0%B2%A8%E0%B2%BF%E0%B2%97%E0%B2%B3%E0%B3%81
https://ml.wikipedia.org/wiki/%E0%B4%87%E0%B4%A8%E0%B5%8D%E0%B4%A4%E0%B5%8D%E0%B4%AF%E0%B4%AF%E0%B4%BF%E0%B4%B2%E0%B5%86_%E0%B4%B8%E0%B4%82%E0%B4%B8%E0%B5%8D%E0%B4%A5%E0%B4%BE%E0%B4%A8%E0%B4%99%E0%B5%8D%E0%B4%99%E0%B4%B3%E0%B5%81%E0%B4%9F%E0%B5%86%E0%B4%AF%E0%B5%81%E0%B4%82_%E0%B4%95%E0%B5%87%E0%B4%A8%E0%B5%8D%E0%B4%A6%E0%B5%8D%E0%B4%B0%E0%B4%AD%E0%B4%B0%E0%B4%A3%E0%B4%AA%E0%B5%8D%E0%B4%B0%E0%B4%A6%E0%B5%87%E0%B4%B6%E0%B4%99%E0%B5%8D%E0%B4%99%E0%B4%B3%E0%B5%81%E0%B4%9F%E0%B5%86%E0%B4%AF%E0%B5%81%E0%B4%82_%E0%B4%A4%E0%B4%B2%E0%B4%B8%E0%B5%8D%E0%B4%A5%E0%B4%BE%E0%B4%A8%E0%B4%99%E0%B5%8D%E0%B4%99%E0%B4%B3%E0%B5%81%E0%B4%9F%E0%B5%86_%E0%B4%AA%E0%B4%9F%E0%B5%8D%E0%B4%9F%E0%B4%BF%E0%B4%95
https://mr.wikipedia.org/wiki/%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4%E0%A4%BE%E0%A4%9A%E0%A5%8D%E0%A4%AF%E0%A4%BE_%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A5%8D%E0%A4%AF%E0%A5%87_%E0%A4%86%E0%A4%A3%E0%A4%BF_%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%A6%E0%A5%87%E0%A4%B6%E0%A4%BE%E0%A4%82%E0%A4%9A%E0%A5%8D%E0%A4%AF%E0%A4%BE_%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A4%A7%E0%A4%BE%E0%A4%A8%E0%A5%80%E0%A4%9A%E0%A5%80_%E0%A4%B6%E0%A4%B9%E0%A4%B0%E0%A5%87
https://ne.wikipedia.org/wiki/%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4%E0%A4%95%E0%A4%BE_%E0%A4%AA%E0%A5%8D%E0%A4%B0%E0%A4%BE%E0%A4%A8%E0%A5%8D%E0%A4%A4_%E0%A4%A4%E0%A4%A5%E0%A4%BE_%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A4%A7%E0%A4%BE%E0%A4%A8%E0%A5%80%E0%A4%B9%E0%A4%B0%E0%A5%81
https://or.wikipedia.org/wiki/%E0%AC%AD%E0%AC%BE%E0%AC%B0%E0%AC%A4%E0%AC%B0_%E0%AC%B0%E0%AC%BE%E0%AC%9C%E0%AD%8D%E0%AD%9F_%E0%AC%93_%E0%AC%95%E0%AD%87%E0%AC%A8%E0%AD%8D%E0%AC%A6%E0%AD%8D%E0%AC%B0%E0%AC%B6%E0%AC%BE%E0%AC%B8%E0%AC%BF%E0%AC%A4_%E0%AC%85%E0%AC%9E%E0%AD%8D%E0%AC%9A%E0%AC%B3%E0%AC%AE%E0%AC%BE%E0%AC%A8%E0%AC%99%E0%AD%8D%E0%AC%95_%E0%AC%B0%E0%AC%BE%E0%AC%9C%E0%AC%A7%E0%AC%BE%E0%AC%A8%E0%AD%80_%E0%AC%A4%E0%AC%BE%E0%AC%B2%E0%AC%BF%E0%AC%95%E0%AC%BE
https://pa.wikipedia.org/wiki/%E0%A8%AD%E0%A8%BE%E0%A8%B0%E0%A8%A4_%E0%A8%A6%E0%A9%87_%E0%A8%B0%E0%A8%BE%E0%A8%9C%E0%A8%BE%E0%A8%82_%E0%A8%85%E0%A8%A4%E0%A9%87_%E0%A8%95%E0%A9%87%E0%A8%82%E0%A8%A6%E0%A8%B0%E0%A9%80_%E0%A8%B8%E0%A8%BC%E0%A8%BE%E0%A8%B8%E0%A8%BC%E0%A8%A4_%E0%A8%AA%E0%A9%8D%E0%A8%B0%E0%A8%A6%E0%A9%87%E0%A8%B8%E0%A8%BE%E0%A8%82_%E0%A8%A6%E0%A9%80_%E0%A8%B8%E0%A9%82%E0%A8%9A%E0%A9%80
https://pnb.wikipedia.org/wiki/%D9%84%D8%B3%D9%B9_%D8%A8%DA%BE%D8%A7%D8%B1%D8%AA_%D8%AF%DB%8C%D8%A7%DA%BA_%D8%B1%DB%8C%D8%A7%D8%B3%D8%AA%D8%A7%DA%BA_%D8%AA%DB%92_%D8%B9%D9%84%D8%A7%D9%82%DB%92_%D8%A8%D9%84%D8%AD%D8%A7%D8%B8_%D8%AF%D8%A7%D8%B1%D8%A7%D9%84%D8%AD%DA%A9%D9%88%D9%85%D8%AA
https://pt.wikipedia.org/wiki/Lista_das_capitais_dos_estados_e_territ%C3%B3rios_da_uni%C3%A3o_da_%C3%8Dndia
https://sr.wikipedia.org/wiki/%D0%94%D1%80%D0%B6%D0%B0%D0%B2%D0%B5_%D0%B8_%D1%82%D0%B5%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%98%D0%B5_%D0%98%D0%BD%D0%B4%D0%B8%D1%98%D0%B5
https://sh.wikipedia.org/wiki/Dr%C5%BEave_i_teritorije_Indije
https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_huvudst%C3%A4der_i_Indien
https://ta.wikipedia.org/wiki/%E0%AE%87%E0%AE%A8%E0%AF%8D%E0%AE%A4%E0%AE%BF%E0%AE%AF_%E0%AE%AE%E0%AE%BE%E0%AE%A8%E0%AE%BF%E0%AE%B2%E0%AE%99%E0%AF%8D%E0%AE%95%E0%AE%B3%E0%AE%BF%E0%AE%A9%E0%AF%8D_%E0%AE%A4%E0%AE%B2%E0%AF%88%E0%AE%A8%E0%AE%95%E0%AE%B0%E0%AE%99%E0%AF%8D%E0%AE%95%E0%AE%B3%E0%AF%81%E0%AE%AE%E0%AF%8D_%E0%AE%92%E0%AE%A9%E0%AF%8D%E0%AE%B1%E0%AE%BF%E0%AE%AF%E0%AE%AA%E0%AF%8D_%E0%AE%AA%E0%AE%95%E0%AF%81%E0%AE%A4%E0%AE%BF%E0%AE%95%E0%AE%B3%E0%AE%BF%E0%AE%A9%E0%AF%8D_%E0%AE%A4%E0%AE%B2%E0%AF%88%E0%AE%A8%E0%AE%95%E0%AE%B0%E0%AE%99%E0%AF%8D%E0%AE%95%E0%AE%B3%E0%AF%81%E0%AE%AE%E0%AF%8D
https://te.wikipedia.org/wiki/%E0%B0%AD%E0%B0%BE%E0%B0%B0%E0%B0%A4_%E0%B0%A6%E0%B1%87%E0%B0%B6_%E0%B0%B0%E0%B0%BE%E0%B0%B7%E0%B1%8D%E0%B0%9F%E0%B1%8D%E0%B0%B0,_%E0%B0%95%E0%B1%87%E0%B0%82%E0%B0%A6%E0%B1%8D%E0%B0%B0_%E0%B0%AA%E0%B0%BE%E0%B0%B2%E0%B0%BF%E0%B0%A4_%E0%B0%AA%E0%B1%8D%E0%B0%B0%E0%B0%BE%E0%B0%82%E0%B0%A4%E0%B0%BE%E0%B0%B2_%E0%B0%B0%E0%B0%BE%E0%B0%9C%E0%B0%A7%E0%B0%BE%E0%B0%A8%E0%B1%81%E0%B0%B2%E0%B1%81
https://ur.wikipedia.org/wiki/%D9%81%DB%81%D8%B1%D8%B3%D8%AA_%D8%A8%DA%BE%D8%A7%D8%B1%D8%AA%DB%8C_%D8%B1%DB%8C%D8%A7%D8%B3%D8%AA%DB%8C%DA%BA_%D8%A7%D9%88%D8%B1_%D8%B9%D9%84%D8%A7%D9%82%DB%81_%D8%AC%D8%A7%D8%AA_%D8%A8%D9%84%D8%AD%D8%A7%D8%B8_%D8%AF%D8%A7%D8%B1%D8%A7%D9%84%D8%AD%DA%A9%D9%88%D9%85%D8%AA
https://zh.wikipedia.org/wiki/%E5%8D%B0%E5%BA%A6%E5%90%84%E9%82%A6%E5%92%8C%E4%B8%AD%E5%A4%AE%E7%9B%B4%E8%BE%96%E5%8C%BA%E9%A6%96%E5%BA%9C%E5%88%97%E8%A1%A8
https://www.wikidata.org/wiki/Special:EntityPage/Q3518799#sitelinks-wikipedia
//en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License
//creativecommons.org/licenses/by-sa/3.0/
//wikimediafoundation.org/wiki/Terms_of_Use
//wikimediafoundation.org/wiki/Privacy_policy
//www.wikimediafoundation.org/
https://wikimediafoundation.org/wiki/Privacy_policy
/wiki/Wikipedia:About
/wiki/Wikipedia:General_disclaimer
//en.wikipedia.org/wiki/Wikipedia:Contact_us
https://www.mediawiki.org/wiki/Special:MyLanguage/How_to_contribute

In [16]:
all_tables=soup.find_all('table') #extact information between <table> </table> tags

In [17]:
right_table=soup.find('table', class_='wikitable sortable plainrowheaders')
right_table

<table class="wikitable sortable plainrowheaders">\n<tr>\n<th scope="col">No.</th>\n<th scope="col">State or<br/>\nunion territory</th>\n<th scope="col">Administrative capitals</th>\n<th scope="col">Legislative capitals</th>\n<th scope="col">Judiciary capitals</th>\n<th scope="col">Year capital was established</th>\n<th scope="col">The Former capital</th>\n</tr>\n<tr>\n<td>1</td>\n<th scope="row"><a href="/wiki/Andaman_and_Nicobar_Islands" title="Andaman and Nicobar Islands">Andaman and Nicobar Islands</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/Port_Blair" title="Port Blair">Port Blair</a></b></td>\n<td>Port Blair</td>\n<td><a href="/wiki/Kolkata" title="Kolkata">Kolkata</a></td>\n<td>1955</td>\n<td>Calcutta (1945\u20131956)</td>\n</tr>\n<tr>\n<td>2</td>\n<th scope="row"><a href="/wiki/Andhra_Pradesh" title="Andhra Pradesh">Andhra Pradesh</a></th>\n<td><a class="mw-redirect" href="/wiki/Hyderabad,_India" title="Hyderabad, India"><b>Hyderabad</b></a> <small>(<i>de jure</i> to 2024)</small><br/>\n<b><a href="/wiki/Amaravati" title="Amaravati">Amaravati</a></b> <small>(<i>de facto</i> from 2017)</small><sup class="reference" id="cite_ref-3"><a href="#cite_note-3">[3]</a></sup> <sup class="reference" id="cite_ref-4"><a href="#cite_note-4">[4]</a></sup> <sup class="reference" id="cite_ref-5"><a href="#cite_note-5">[a]</a></sup></td>\n<td><a href="/wiki/Amaravati" title="Amaravati">Amaravati</a> <sup class="reference" id="cite_ref-6"><a href="#cite_note-6">[5]</a></sup></td>\n<td><a href="/wiki/High_Court_of_Judicature_at_Hyderabad" title="High Court of Judicature at Hyderabad">Hyderabad</a></td>\n<td>1956<br/>\n2017</td>\n<td><a href="/wiki/Kurnool" title="Kurnool">Kurnool</a> (1953-1956)</td>\n</tr>\n<tr>\n<td>3</td>\n<th scope="row"><a href="/wiki/Arunachal_Pradesh" title="Arunachal Pradesh">Arunachal Pradesh</a></th>\n<td><b><a href="/wiki/Itanagar" title="Itanagar">Itanagar</a></b></td>\n<td>Itanagar</td>\n<td><a href="/wiki/Guwahati" title="Guwahati">Guwahati</a></td>\n<td>1986</td>\n<td></td>\n</tr>\n<tr>\n<td>4</td>\n<th scope="row"><a href="/wiki/Assam" title="Assam">Assam</a></th>\n<td><b><a href="/wiki/Dispur" title="Dispur">Dispur</a></b></td>\n<td><a href="/wiki/Guwahati" title="Guwahati">Guwahati</a></td>\n<td>Guwahati</td>\n<td>1975</td>\n<td><a href="/wiki/Shillong" title="Shillong">Shillong</a><sup class="reference" id="cite_ref-8"><a href="#cite_note-8">[b]</a></sup> (1874\u20131972)</td>\n</tr>\n<tr>\n<td>5</td>\n<th scope="row"><a href="/wiki/Bihar" title="Bihar">Bihar</a></th>\n<td><b><a href="/wiki/Patna" title="Patna">Patna</a></b></td>\n<td>Patna</td>\n<td>Patna</td>\n<td>1912</td>\n<td></td>\n</tr>\n<tr>\n<td>6</td>\n<th scope="row"><a href="/wiki/Chandigarh" title="Chandigarh">Chandigarh</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/Chandigarh" title="Chandigarh">Chandigarh</a></b><sup class="reference" id="cite_ref-10"><a href="#cite_note-10">[c]</a></sup></td>\n<td>\xa0\u2014</td>\n<td>Chandigarh</td>\n<td>1966</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>7</td>\n<th scope="row"><a href="/wiki/Chhattisgarh" title="Chhattisgarh">Chhattisgarh</a></th>\n<td><b><a href="/wiki/Naya_Raipur" title="Naya Raipur">Naya Raipur</a></b><sup class="reference" id="cite_ref-11"><a href="#cite_note-11">[d]</a></sup></td>\n<td>Raipur</td>\n<td><a href="/wiki/Bilaspur,_Chhattisgarh" title="Bilaspur, Chhattisgarh">Bilaspur</a></td>\n<td>2000</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>8</td>\n<th scope="row"><a href="/wiki/Dadra_and_Nagar_Haveli" title="Dadra and Nagar Haveli">Dadra and Nagar Haveli</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/Silvassa" title="Silvassa">Silvassa</a></b></td>\n<td>\xa0\u2014</td>\n<td><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a></td>\n<td>1945</td>\n<td>Mumbai (1954\u20131961)<br/>\n<a href="/wiki/Panaji" title="Panaji">Panaji</a> (1961\u20131987)</td>\n</tr>\n<tr>\n<td>9</td>\n<th scope="row"><a href="/wiki/Daman_and_Diu" title="Daman and Diu">Daman and Diu</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/Daman,_Daman_and_Diu" title="Daman, Daman and Diu">Daman</a></b></td>\n<td>\xa0\u2014</td>\n<td><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a></td>\n<td>1987</td>\n<td><a href="/wiki/Ahmedabad" title="Ahmedabad">Ahmedabad</a> (1961\u20131963)<br/>\n<a href="/wiki/Panaji" title="Panaji">Panaji</a> (1963\u20131987)</td>\n</tr>\n<tr>\n<td>10</td>\n<th scope="row"><a class="mw-redirect" href="/wiki/Delhi_NCT" title="Delhi NCT">National Capital Territory of Delhi</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/New_Delhi" title="New Delhi">New Delhi</a></b></td>\n<td>New Delhi</td>\n<td>New Delhi</td>\n<td>1931</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>11</td>\n<th scope="row"><a href="/wiki/Goa" title="Goa">Goa</a></th>\n<td><b><a href="/wiki/Panaji" title="Panaji">Panaji</a></b><sup class="reference" id="cite_ref-13"><a href="#cite_note-13">[e]</a></sup></td>\n<td><a href="/wiki/Porvorim" title="Porvorim">Porvorim</a></td>\n<td><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a></td>\n<td>1961</td>\n<td>Panaji (1961\u20131987)</td>\n</tr>\n<tr>\n<td>12</td>\n<th scope="row"><a href="/wiki/Gujarat" title="Gujarat">Gujarat</a></th>\n<td><b><a href="/wiki/Gandhinagar" title="Gandhinagar">Gandhinagar</a></b></td>\n<td>Gandhinagar</td>\n<td><a href="/wiki/Ahmedabad" title="Ahmedabad">Ahmedabad</a></td>\n<td>1960</td>\n<td><a href="/wiki/Ahmedabad" title="Ahmedabad">Ahmedabad</a> (1960\u20131970)</td>\n</tr>\n<tr>\n<td>13</td>\n<th scope="row"><a href="/wiki/Haryana" title="Haryana">Haryana</a></th>\n<td><b><a href="/wiki/Chandigarh" title="Chandigarh">Chandigarh</a></b></td>\n<td>Chandigarh</td>\n<td>Chandigarh</td>\n<td>1966</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>14</td>\n<th scope="row"><a href="/wiki/Himachal_Pradesh" title="Himachal Pradesh">Himachal Pradesh</a></th>\n<td><b><a href="/wiki/Shimla" title="Shimla">Shimla</a></b>\n<p><a href="/wiki/Dharamsala" title="Dharamsala"><b>Dharamshala</b></a> (W/2nd)<sup class="reference" id="cite_ref-14"><a href="#cite_note-14">[9]</a></sup></p>\n</td>\n<td>Shimla\xa0(Summer)\n<p>Dharamsala(Winter)</p>\n</td>\n<td>Shimla\xa0</td>\n<td>1971\n<p>2017</p>\n</td>\n<td><a href="/wiki/Bilaspur,_Himachal_Pradesh" title="Bilaspur, Himachal Pradesh">Bilaspur</a> (1950\u20131956)</td>\n</tr>\n<tr>\n<td>15</td>\n<th scope="row"><a href="/wiki/Jammu_and_Kashmir" title="Jammu and Kashmir">Jammu and Kashmir</a></th>\n<td><b><a href="/wiki/Srinagar" title="Srinagar">Srinagar</a></b>\xa0(Summer)<br/>\n<b><a href="/wiki/Jammu" title="Jammu">Jammu</a></b>\xa0(Winter)</td>\n<td>Srinagar\xa0(Summer)<br/>\nJammu\xa0(Winter)</td>\n<td>Srinagar\xa0(Summer)<br/>\nJammu\xa0(Winter)</td>\n<td>1947</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>16</td>\n<th scope="row"><a href="/wiki/Jharkhand" title="Jharkhand">Jharkhand</a></th>\n<td><b><a href="/wiki/Ranchi" title="Ranchi">Ranchi</a></b></td>\n<td>Ranchi</td>\n<td>Ranchi</td>\n<td>2000</td>\n<td></td>\n</tr>\n<tr>\n<td>17</td>\n<th scope="row"><a href="/wiki/Karnataka" title="Karnataka">Karnataka</a></th>\n<td><b><a class="mw-redirect" href="/wiki/Bengaluru" title="Bengaluru">Bengaluru</a></b></td>\n<td>Bengaluru</td>\n<td>Bengaluru</td>\n<td>1940</td>\n<td>(Mysore)</td>\n</tr>\n<tr>\n<td>18</td>\n<th scope="row"><a href="/wiki/Kerala" title="Kerala">Kerala</a></th>\n<td><b><a href="/wiki/Thiruvananthapuram" title="Thiruvananthapuram">Thiruvananthapuram</a></b></td>\n<td>Thiruvananthapuram</td>\n<td><a href="/wiki/Kochi" title="Kochi">Kochi</a></td>\n<td>1956</td>\n<td></td>\n</tr>\n<tr>\n<td>19</td>\n<th scope="row"><a href="/wiki/Lakshadweep" title="Lakshadweep">Lakshadweep</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/Kavaratti" title="Kavaratti">Kavaratti</a></b></td>\n<td>Kavaratti</td>\n<td><a href="/wiki/Kochi" title="Kochi">Kochi</a></td>\n<td>1956</td>\n<td></td>\n</tr>\n<tr>\n<td>20</td>\n<th scope="row"><a href="/wiki/Madhya_Pradesh" title="Madhya Pradesh">Madhya Pradesh</a></th>\n<td><b><a href="/wiki/Bhopal" title="Bhopal">Bhopal</a></b></td>\n<td>Bhopal</td>\n<td><a href="/wiki/Jabalpur" title="Jabalpur">Jabalpur</a></td>\n<td>1956</td>\n<td><a href="/wiki/Nagpur" title="Nagpur">Nagpur</a><sup class="reference" id="cite_ref-18"><a href="#cite_note-18">[f]</a></sup> (1861\u20131956)</td>\n</tr>\n<tr>\n<td>21</td>\n<th scope="row"><a href="/wiki/Maharashtra" title="Maharashtra">Maharashtra</a></th>\n<td><b><a href="/wiki/Mumbai" title="Mumbai">Mumbai</a></b><sup class="reference" id="cite_ref-19"><a href="#cite_note-19">[g]</a></sup><br/>\n<b><a href="/wiki/Nagpur" title="Nagpur">Nagpur</a></b>\xa0(W/2nd)<sup class="reference" id="cite_ref-20"><a href="#cite_note-20">[h]</a></sup></td>\n<td>Mumbai\xa0(S+B)<br/>\nNagpur\xa0(W)<sup class="reference" id="cite_ref-22"><a href="#cite_note-22">[i]</a></sup></td>\n<td>Mumbai</td>\n<td>1818<br/>\n1960</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>22</td>\n<th scope="row"><a href="/wiki/Manipur" title="Manipur">Manipur</a></th>\n<td><b><a href="/wiki/Imphal" title="Imphal">Imphal</a></b></td>\n<td>Imphal</td>\n<td>Imphal</td>\n<td>1947</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>23</td>\n<th scope="row"><a href="/wiki/Meghalaya" title="Meghalaya">Meghalaya</a></th>\n<td><b><a href="/wiki/Shillong" title="Shillong">Shillong</a></b></td>\n<td>Shillong</td>\n<td>Shillong</td>\n<td>1970</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>24</td>\n<th scope="row"><a href="/wiki/Mizoram" title="Mizoram">Mizoram</a></th>\n<td><b><a href="/wiki/Aizawl" title="Aizawl">Aizawl</a></b></td>\n<td>Aizawl</td>\n<td><a href="/wiki/Guwahati" title="Guwahati">Guwahati</a></td>\n<td>1972</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>25</td>\n<th scope="row"><a href="/wiki/Nagaland" title="Nagaland">Nagaland</a></th>\n<td><b><a href="/wiki/Kohima" title="Kohima">Kohima</a></b></td>\n<td>Kohima</td>\n<td><a href="/wiki/Guwahati" title="Guwahati">Guwahati</a></td>\n<td>1963</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>26</td>\n<th scope="row"><a href="/wiki/Odisha" title="Odisha">Odisha</a></th>\n<td><b><a href="/wiki/Bhubaneswar" title="Bhubaneswar">Bhubaneswar</a></b></td>\n<td>Bhubaneswar</td>\n<td><a href="/wiki/Cuttack" title="Cuttack">Cuttack</a></td>\n<td>1948</td>\n<td><a href="/wiki/Cuttack" title="Cuttack">Cuttack</a> (1936\u20131948)</td>\n</tr>\n<tr>\n<td>27</td>\n<th scope="row"><a href="/wiki/Puducherry" title="Puducherry">Puducherry</a> <img alt="union territory" data-file-height="14" data-file-width="9" height="14" src="//upload.wikimedia.org/wikipedia/commons/3/37/Dagger-14-plain.png" width="9"/></th>\n<td><b><a href="/wiki/Puducherry" title="Puducherry">Puducherry</a></b></td>\n<td>Puducherry</td>\n<td><a href="/wiki/Chennai" title="Chennai">Chennai</a></td>\n<td>1954</td>\n<td><a class="mw-redirect" href="/wiki/Madras" title="Madras">Madras</a> (1948\u20131954)</td>\n</tr>\n<tr>\n<td>28</td>\n<th scope="row"><a href="/wiki/Punjab,_India" title="Punjab, India">Punjab</a></th>\n<td><b><a href="/wiki/Chandigarh" title="Chandigarh">Chandigarh</a></b></td>\n<td>Chandigarh</td>\n<td>Chandigarh</td>\n<td>1966</td>\n</tr>\n<tr>\n<td>29</td>\n<th scope="row"><a href="/wiki/Rajasthan" title="Rajasthan">Rajasthan</a></th>\n<td><b><a href="/wiki/Jaipur" title="Jaipur">Jaipur</a></b></td>\n<td>Jaipur</td>\n<td><a href="/wiki/Jodhpur" title="Jodhpur">Jodhpur</a></td>\n<td>1950</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>30</td>\n<th scope="row"><a href="/wiki/Sikkim" title="Sikkim">Sikkim</a></th>\n<td><b><a href="/wiki/Gangtok" title="Gangtok">Gangtok</a></b><sup class="reference" id="cite_ref-24"><a href="#cite_note-24">[j]</a></sup></td>\n<td>Gangtok</td>\n<td>Gangtok</td>\n<td>1890</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>31</td>\n<th scope="row"><a href="/wiki/Tamil_Nadu" title="Tamil Nadu">Tamil Nadu</a></th>\n<td><b><a href="/wiki/Chennai" title="Chennai">Chennai</a></b><sup class="reference" id="cite_ref-25"><a href="#cite_note-25">[k]</a></sup></td>\n<td>Chennai</td>\n<td>Chennai</td>\n<td>1956</td>\n<td>\xa0</td>\n</tr>\n<tr>\n<td>32</td>\n<th scope="row"><a href="/wiki/Telangana" title="Telangana">Telangana</a></th>\n<td><b><a href="/wiki/Hyderabad" title="Hyderabad">Hyderabad</a></b><sup class="reference" id="cite_ref-26"><a href="#cite_note-26">[l]</a></sup></td>\n<td>Hyderabad</td>\n<td>Hyderabad</td>\n<td>2014</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>33</td>\n<th scope="row"><a href="/wiki/Tripura" title="Tripura">Tripura</a></th>\n<td><b><a href="/wiki/Agartala" title="Agartala">Agartala</a></b></td>\n<td>Agartala</td>\n<td>Agartala</td>\n<td>1956</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>34</td>\n<th scope="row"><a href="/wiki/Uttar_Pradesh" title="Uttar Pradesh">Uttar Pradesh</a></th>\n<td><b><a href="/wiki/Lucknow" title="Lucknow">Lucknow</a></b></td>\n<td>Lucknow</td>\n<td><a href="/wiki/Allahabad" title="Allahabad">Allahabad</a></td>\n<td>1938</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>35</td>\n<th scope="row"><a href="/wiki/Uttarakhand" title="Uttarakhand">Uttarakhand</a></th>\n<td><b><a href="/wiki/Dehradun" title="Dehradun">Dehradun</a></b><sup class="reference" id="cite_ref-28"><a href="#cite_note-28">[m]</a></sup></td>\n<td>Dehradun</td>\n<td><a href="/wiki/Nainital" title="Nainital">Nainital</a></td>\n<td>2000</td>\n<td>\xa0\u2014</td>\n</tr>\n<tr>\n<td>36</td>\n<th scope="row"><a href="/wiki/West_Bengal" title="West Bengal">West Bengal</a></th>\n<td><b><a href="/wiki/Kolkata" title="Kolkata">Kolkata</a></b></td>\n<td>Kolkata</td>\n<td>Kolkata</td>\n<td>1947</td>\n<td>\xa0</td>\n</tr>\n</table>

In [21]:
#Generate lists
A=[]
B=[]
C=[]
D=[]
E=[]
F=[]
G=[]
for row in right_table.findAll("tr"):
    cells = row.findAll('td')
    states=row.findAll('th') #To store second column data
    if len(cells)==6: #Only extract table body not heading
        A.append(cells[0].find(text=True))
        B.append(states[0].find(text=True))
        C.append(cells[1].find(text=True))
        D.append(cells[2].find(text=True))
        E.append(cells[3].find(text=True))
        F.append(cells[4].find(text=True))
        G.append(cells[5].find(text=True))

In [22]:
df=pd.DataFrame(A,columns=['Number'])
df['State/UT']=B
df['Admin_Capital']=C
df['Legislative_Capital']=D
df['Judiciary_Capital']=E
df['Year_Capital']=F
df['Former_Capital']=G
df

,Number,State/UT,Admin_Capital,Legislative_Capital,Judiciary_Capital,Year_Capital,Former_Capital
0,1,Andaman and Nicobar Islands,Port Blair,Port Blair,Kolkata,1955,Calcutta (1945–1956)
1,2,Andhra Pradesh,Hyderabad,Amaravati,Hyderabad,1956,Kurnool
2,3,Arunachal Pradesh,Itanagar,Itanagar,Guwahati,1986,None
3,4,Assam,Dispur,Guwahati,Guwahati,1975,Shillong
4,5,Bihar,Patna,Patna,Patna,1912,None
5,6,Chandigarh,Chandigarh,—,Chandigarh,1966,—
6,7,Chhattisgarh,Naya Raipur,Raipur,Bilaspur,2000,—
7,8,Dadra and Nagar Haveli,Silvassa,—,Mumbai,1945,Mumbai (1954–1961)
8,9,Daman and Diu,Daman,—,Mumbai,1987,Ahmedabad
9,10,National Capital Territory of Delhi,New Delhi,New Delhi,New Delhi,1931,—
10,11,Goa,Panaji,Porvorim,Mumbai,1961,Panaji (1961–1987)
11,12,Gujarat,Gandhinagar,Gandhinagar,Ahmedabad,1960,Ahmedabad
12,13,Haryana,Chandigarh,Chandigarh,Chandigarh,1966,—
13,14,Himachal Pradesh,Shimla,Shimla (Summer),Shimla,1971,Bilaspur
14,15,Jammu and Kashmir,Srinagar,Srinagar (Summer),Srinagar (Summer),1947,—
15,16,Jharkhand,Ranchi,Ranchi,Ranchi,2000,None
16,17,Karnataka,Bengaluru,Bengaluru,Bengaluru,1940,(Mysore)
17,18,Kerala,Thiruvananthapuram,Thiruvananthapuram,Kochi,1956,None
18,19,Lakshadweep,Kavaratti,Kavaratti,Kochi,1956,None
19,20,Madhya Pradesh,Bhopal,Bhopal,Jabalpur,1956,Nagpur
20,21,Maharashtra,Mumbai,Mumbai (S+B),Mumbai,1818,—
21,22,Manipur,Imphal,Imphal,Imphal,1947,—
22,23,Meghalaya,Shillong,Shillong,Shillong,1970,—
23,24,Mizoram,Aizawl,Aizawl,Guwahati,1972,—
24,25,Nagaland,Kohima,Kohima,Guwahati,1963,—
25,26,Odisha,Bhubaneswar,Bhubaneswar,Cuttack,1948,Cuttack
26,27,Puducherry,Puducherry,Puducherry,Chennai,1954,Madras
27,29,Rajasthan,Jaipur,Jaipur,Jodhpur,1950,—
28,30,Sikkim,Gangtok,Gangtok,Gangtok,1890,—
29,31,Tamil Nadu,Chennai,Chennai,Chennai,1956,
30,32,Telangana,Hyderabad,Hyderabad,Hyderabad,2014,—
31,33,Tripura,Agartala,Agartala,Agartala,1956,—
32,34,Uttar Pradesh,Lucknow,Lucknow,Allahabad,1938,—
33,35,Uttarakhand,Dehradun,Dehradun,Nainital,2000,—
34,36,West Bengal,Kolkata,Kolkata,Kolkata,1947,